name: Sprint Package Deployment on QA org
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      PACKAGE_VERSION:
        description: 'Package Version'
        required: true
        default: '1.15'
env:
  SF_PACKAGE_VERSION: ${{ github.event.inputs.PACKAGE_VERSION }}
  WORKSPACE: ${{ github.workspace }}
  JOB_NAME: ${{ github.job }}
  BUILD_NUMBER : ${{ github.run_number }}
  BRANCH_NAME: ${{ github.ref }}
  RUN_BY: ${{ github.actor }}
  # PKG_NAMESPACE: 'BPTestAPI'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
